/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as HealthRouteImport } from './routes/health'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as AppointmentsAppointmentIdRouteImport } from './routes/appointments.$appointmentId'
import { Route as ConditionsConditionIdRouteImport } from './routes/conditions.$conditionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsAppointmentIdRoute =
  AppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => AppointmentsRoute,
  } as any)
const ConditionsConditionIdRoute = ConditionsConditionIdRouteImport.update({
  id: '/$conditionId',
  path: '/$conditionId',
  getParentRoute: () => ConditionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/conditions': typeof ConditionsRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/health': typeof HealthRoute
  '/measurements': typeof MeasurementsRoute
  '/medications': typeof MedicationsRoute
  '/nutrition': typeof NutritionRoute
  '/symptoms': typeof SymptomsRoute
  '/timeline': typeof TimelineRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/conditions/$conditionId': typeof ConditionsConditionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/conditions': typeof ConditionsRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/health': typeof HealthRoute
  '/measurements': typeof MeasurementsRoute
  '/medications': typeof MedicationsRoute
  '/nutrition': typeof NutritionRoute
  '/symptoms': typeof SymptomsRoute
  '/timeline': typeof TimelineRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/conditions/$conditionId': typeof ConditionsConditionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/conditions': typeof ConditionsRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/health': typeof HealthRoute
  '/measurements': typeof MeasurementsRoute
  '/medications': typeof MedicationsRoute
  '/nutrition': typeof NutritionRoute
  '/symptoms': typeof SymptomsRoute
  '/timeline': typeof TimelineRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/conditions/$conditionId': typeof ConditionsConditionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/conditions'
    | '/doctors'
    | '/health'
    | '/measurements'
    | '/medications'
    | '/nutrition'
    | '/symptoms'
    | '/timeline'
    | '/appointments/$appointmentId'
    | '/conditions/$conditionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/conditions'
    | '/doctors'
    | '/health'
    | '/measurements'
    | '/medications'
    | '/nutrition'
    | '/symptoms'
    | '/timeline'
    | '/appointments/$appointmentId'
    | '/conditions/$conditionId'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/conditions'
    | '/doctors'
    | '/health'
    | '/measurements'
    | '/medications'
    | '/nutrition'
    | '/symptoms'
    | '/timeline'
    | '/appointments/$appointmentId'
    | '/conditions/$conditionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  ConditionsRoute: typeof ConditionsRouteWithChildren
  DoctorsRoute: typeof DoctorsRoute
  HealthRoute: typeof HealthRoute
  MeasurementsRoute: typeof MeasurementsRoute
  MedicationsRoute: typeof MedicationsRoute
  NutritionRoute: typeof NutritionRoute
  SymptomsRoute: typeof SymptomsRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$appointmentId': {
      id: '/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppointmentsAppointmentIdRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/conditions/$conditionId': {
      id: '/conditions/$conditionId'
      path: '/$conditionId'
      fullPath: '/conditions/$conditionId'
      preLoaderRoute: typeof ConditionsConditionIdRouteImport
      parentRoute: typeof ConditionsRoute
    }
  }
}

interface AppointmentsRouteChildren {
  AppointmentsAppointmentIdRoute: typeof AppointmentsAppointmentIdRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsAppointmentIdRoute: AppointmentsAppointmentIdRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

interface ConditionsRouteChildren {
  ConditionsConditionIdRoute: typeof ConditionsConditionIdRoute
}

const ConditionsRouteChildren: ConditionsRouteChildren = {
  ConditionsConditionIdRoute: ConditionsConditionIdRoute,
}

const ConditionsRouteWithChildren = ConditionsRoute._addFileChildren(
  ConditionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  ConditionsRoute: ConditionsRouteWithChildren,
  DoctorsRoute: DoctorsRoute,
  HealthRoute: HealthRoute,
  MeasurementsRoute: MeasurementsRoute,
  MedicationsRoute: MedicationsRoute,
  NutritionRoute: NutritionRoute,
  SymptomsRoute: SymptomsRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
